"""initial_schema

Revision ID: ccbf2e1efafb
Revises: 
Create Date: 2026-05-27 23:58:06.431871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccbf2e1efafb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('payload_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('bank_holiday_calendar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('holiday_type', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'holiday_date')
    )
    op.create_index('idx_holiday_date', 'bank_holiday_calendar', ['holiday_date'], unique=False, postgresql_where='is_active = TRUE')
    op.create_table('charge_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('charge_code', sa.String(length=50), nullable=False),
    sa.Column('charge_name', sa.String(length=100), nullable=False),
    sa.Column('calc_type', sa.String(length=20), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pct_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gst_applicable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), server_default='18.00', nullable=False),
    sa.Column('penal_capitalise', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_till', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'charge_code', 'effective_from', name='ux_charge_master_active')
    )
    op.create_table('job_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('loan_account_number', sa.String(length=30), nullable=False),
    sa.Column('sanctioned_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('disbursal_utr', sa.String(length=50), nullable=False),
    sa.Column('disbursal_date', sa.Date(), nullable=False),
    sa.Column('disbursal_channel', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_type', sa.String(length=20), nullable=False),
    sa.Column('rate_type', sa.String(length=10), server_default='fixed', nullable=False),
    sa.Column('benchmark_code', sa.String(length=50), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('roi_monthly', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('roi_daily', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('tenure_days', sa.Integer(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_overdue', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_penalty', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_bounce_charges', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('active_mandate_id', sa.UUID(), nullable=True),
    sa.Column('cooling_off_until', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('dpd', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sma_category', sa.String(length=10), nullable=True),
    sa.Column('npa_classification', sa.String(length=20), nullable=True),
    sa.Column('npa_since', sa.Date(), nullable=True),
    sa.Column('first_default_date', sa.Date(), nullable=True),
    sa.Column('provision_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True),
    sa.Column('provision_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_type', sa.String(length=20), nullable=True),
    sa.Column('noc_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('noc_s3_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_account_number')
    )
    op.create_index('idx_loans_dpd', 'loans', ['dpd'], unique=False, postgresql_where="status = 'active'")
    op.create_index('idx_loans_maturity', 'loans', ['maturity_date'], unique=False, postgresql_where="status = 'active'")
    op.create_index(op.f('ix_loans_customer_id'), 'loans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_index(op.f('ix_loans_tenant_id'), 'loans', ['tenant_id'], unique=False)
    op.create_table('payment_allocation_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('bucket', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_type', 'bucket', name='uq_scheme_bucket'),
    sa.UniqueConstraint('tenant_id', 'product_type', 'step_order', name='uq_scheme_step')
    )
    op.create_index('idx_alloc_scheme_lookup', 'payment_allocation_schemes', ['tenant_id', 'product_type', 'step_order'], unique=False, postgresql_where='is_active = TRUE')
    op.create_table('pending_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('maker_id', sa.UUID(), nullable=False),
    sa.Column('maker_role', sa.String(length=50), nullable=False),
    sa.Column('checker_id', sa.UUID(), nullable=True),
    sa.Column('checker_role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_approvals_status', 'pending_approvals', ['tenant_id', 'status', 'expires_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_table('product_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('interest_type', sa.String(length=20), nullable=False),
    sa.Column('foreclosure_allowed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('foreclosure_lock_months', sa.Integer(), server_default='0', nullable=False),
    sa.Column('grace_period_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enach_presentation_lead_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('part_prepayment_allowed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('part_prepayment_min_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('part_prepayment_lock_months', sa.Integer(), server_default='0', nullable=False),
    sa.Column('restructuring_allowed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ots_allowed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('noc_auto_issue_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('bureau_report_on_closure', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_till', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_code', 'effective_from', name='ux_product_master_active')
    )
    op.create_table('regulatory_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('reporting_period', sa.Date(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_s3_key', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'config_key', name='uq_tenant_config')
    )
    op.create_table('collection_rule_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('dpd_from', sa.Integer(), nullable=False),
    sa.Column('dpd_to', sa.Integer(), nullable=False),
    sa.Column('sma_bucket', sa.String(length=10), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('escalate_to_field', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('legal_action_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enach_retry_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('enach_retry_gap_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('notify_agent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notify_guarantor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_till', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collection_rule_dpd', 'collection_rule_master', ['tenant_id', 'dpd_from', 'dpd_to'], unique=False, postgresql_where='is_active = TRUE')
    op.create_table('credit_bureau_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bureau', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('reporting_month', sa.Date(), nullable=False),
    sa.Column('dpd_reported', sa.Integer(), nullable=True),
    sa.Column('account_status', sa.String(length=30), nullable=True),
    sa.Column('outstanding_reported', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('submission_ref', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cross_sell_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('ineligible_reason', sa.String(length=200), nullable=True),
    sa.Column('suggested_product_code', sa.String(length=50), nullable=True),
    sa.Column('suggested_max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cross_sell_eligible', 'cross_sell_flags', ['tenant_id', 'eligible', 'status'], unique=False, postgresql_where="eligible = TRUE AND status = 'pending'")
    op.create_table('loan_guarantors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_restructuring',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('restructure_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('orig_outstanding', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orig_tenure', sa.Integer(), nullable=True),
    sa.Column('orig_roi', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('orig_emi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('new_principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_tenure', sa.Integer(), nullable=False),
    sa.Column('new_roi', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('new_emi', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_maturity_date', sa.Date(), nullable=False),
    sa.Column('moratorium_months', sa.Integer(), server_default='0', nullable=False),
    sa.Column('restructuring_charge', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('gst_on_charge', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_write_offs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('write_off_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('principal_written_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_written_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_written_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('write_off_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('board_resolution_ref', sa.String(length=100), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_to_date', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending_approval', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('umrn', sa.String(length=100), nullable=True),
    sa.Column('vendor_mandate_id', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_masked', sa.String(length=20), nullable=True),
    sa.Column('ifsc', sa.String(length=15), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), server_default='monthly', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('cancellation_reason', sa.String(length=200), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noc_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'status', name='uq_noc_queue_loan')
    )
    op.create_index('idx_noc_queue_pending', 'noc_queue', ['priority', 'created_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_table('npa_provisioning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('dpd_at_eom', sa.Integer(), nullable=False),
    sa.Column('outstanding_eom', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collateral_value', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('provision_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'report_month')
    )
    op.create_table('rate_reset_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('old_roi_monthly', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('new_roi_monthly', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('reset_date', sa.Date(), nullable=False),
    sa.Column('customer_choice', sa.String(length=30), nullable=True),
    sa.Column('consent_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending_consent', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repayment_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_amt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_amt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bounce_charge', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('bounce_gst', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('penalty_amt', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('penalty_gst', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('waiver_amt', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('dpd_on_payment', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_no')
    )
    op.create_index('idx_sched_due_date', 'repayment_schedules', ['due_date'], unique=False, postgresql_where="status IN ('pending', 'overdue', 'partial')")
    op.create_index(op.f('ix_repayment_schedules_loan_id'), 'repayment_schedules', ['loan_id'], unique=False)
    op.create_table('bounce_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_attempted', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bounce_reason', sa.String(length=200), nullable=True),
    sa.Column('npci_ref', sa.String(length=100), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('bounce_charge', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('bounce_gst', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('charge_waived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('waiver_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emi_debit_retry_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('retry_date', sa.Date(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retry_queue_date', 'emi_debit_retry_queue', ['retry_date', 'processed'], unique=False, postgresql_where='processed = FALSE')
    op.create_table('loan_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('allocation_scheme', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_ledger_effective_date'), 'loan_ledger', ['effective_date'], unique=False)
    op.create_index(op.f('ix_loan_ledger_loan_id'), 'loan_ledger', ['loan_id'], unique=False)
    op.create_table('loan_waivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('grievance_ticket', sa.String(length=30), nullable=False),
    sa.Column('waiver_type', sa.String(length=30), nullable=False),
    sa.Column('waiver_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_reversal', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandate_amendment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('old_mandate_id', sa.UUID(), nullable=True),
    sa.Column('new_mandate_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['new_mandate_id'], ['mandates.id'], ),
    sa.ForeignKeyConstraint(['old_mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('utr_ref', sa.String(length=100), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('payer_account', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='initiated', nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('allocated_principal', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('allocated_interest', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('allocated_penalty', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('allocated_bounce', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('excess_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_utr', 'payments', ['utr_ref'], unique=False, postgresql_where='utr_ref IS NOT NULL')
    op.create_index(op.f('ix_payments_loan_id'), 'payments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('penalty_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('accrual_date', sa.Date(), nullable=False),
    sa.Column('dpd_on_date', sa.Integer(), nullable=False),
    sa.Column('overdue_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_type', sa.String(length=20), nullable=False),
    sa.Column('waived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('waiver_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=True),
    sa.Column('waiver_by', sa.UUID(), nullable=True),
    sa.Column('waiver_reason', sa.String(length=500), nullable=True),
    sa.Column('waiver_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'schedule_id', 'accrual_date', name='idx_penalty_date')
    )
    op.create_table('foreclosure_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overdue_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('foreclosure_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_on_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ots_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('offer_valid_until', sa.Date(), nullable=False),
    sa.Column('total_outstanding', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settlement_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('waiver_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('waiver_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_level', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='offered', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_prepayment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('prepay_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prepay_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_on_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_outstanding', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('recalc_option', sa.String(length=20), nullable=True),
    sa.Column('new_emi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('new_tenure_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_link_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_short_url', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_link_id')
    )
    op.create_table('payment_suspense',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source_payment_id', sa.UUID(), nullable=False),
    sa.Column('held_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_to_payment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='holding', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['released_to_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['source_payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_suspense')
    op.drop_table('payment_links')
    op.drop_table('part_prepayment_requests')
    op.drop_table('ots_settlements')
    op.drop_table('foreclosure_requests')
    op.drop_table('penalty_ledger')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_loan_id'), table_name='payments')
    op.drop_index('idx_payments_utr', table_name='payments', postgresql_where='utr_ref IS NOT NULL')
    op.drop_table('payments')
    op.drop_table('mandate_amendment_requests')
    op.drop_table('loan_waivers')
    op.drop_index(op.f('ix_loan_ledger_loan_id'), table_name='loan_ledger')
    op.drop_index(op.f('ix_loan_ledger_effective_date'), table_name='loan_ledger')
    op.drop_table('loan_ledger')
    op.drop_index('idx_retry_queue_date', table_name='emi_debit_retry_queue', postgresql_where='processed = FALSE')
    op.drop_table('emi_debit_retry_queue')
    op.drop_table('bounce_events')
    op.drop_index(op.f('ix_repayment_schedules_loan_id'), table_name='repayment_schedules')
    op.drop_index('idx_sched_due_date', table_name='repayment_schedules', postgresql_where="status IN ('pending', 'overdue', 'partial')")
    op.drop_table('repayment_schedules')
    op.drop_table('rate_reset_requests')
    op.drop_table('npa_provisioning')
    op.drop_index('idx_noc_queue_pending', table_name='noc_queue', postgresql_where="status = 'pending'")
    op.drop_table('noc_queue')
    op.drop_table('mandates')
    op.drop_table('loan_write_offs')
    op.drop_table('loan_restructuring')
    op.drop_table('loan_guarantors')
    op.drop_index('idx_cross_sell_eligible', table_name='cross_sell_flags', postgresql_where="eligible = TRUE AND status = 'pending'")
    op.drop_table('cross_sell_flags')
    op.drop_table('credit_bureau_reports')
    op.drop_index('idx_collection_rule_dpd', table_name='collection_rule_master', postgresql_where='is_active = TRUE')
    op.drop_table('collection_rule_master')
    op.drop_table('tenant_configs')
    op.drop_table('regulatory_reports')
    op.drop_table('product_master')
    op.drop_index('idx_pending_approvals_status', table_name='pending_approvals', postgresql_where="status = 'pending'")
    op.drop_table('pending_approvals')
    op.drop_index('idx_alloc_scheme_lookup', table_name='payment_allocation_schemes', postgresql_where='is_active = TRUE')
    op.drop_table('payment_allocation_schemes')
    op.drop_index(op.f('ix_loans_tenant_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_customer_id'), table_name='loans')
    op.drop_index('idx_loans_maturity', table_name='loans', postgresql_where="status = 'active'")
    op.drop_index('idx_loans_dpd', table_name='loans', postgresql_where="status = 'active'")
    op.drop_table('loans')
    op.drop_table('job_execution_logs')
    op.drop_table('charge_master')
    op.drop_index('idx_holiday_date', table_name='bank_holiday_calendar', postgresql_where='is_active = TRUE')
    op.drop_table('bank_holiday_calendar')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
